name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - id: package-version
        uses: codota/npm-get-version-action@master
      - name: Tag & Package.json Versions Not Matching
        if: ${{ format('v{0}', steps.package-version.outputs.current-version) != env.RELEASE_VERSION}}
        run: exit 1
      - uses: codota/action-setup-atom@v1
        with:
          channel: stable
      - run: apm publish -t ${{ steps.package-version.outputs.current-version }}
        env:
          ATOM_ACCESS_TOKEN: ${{secrets.ATOM_ACCESS_TOKEN}}